apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: Zmxhc2stdXNlcg==  # flask-user (Base64 encoded)
  password: Zmxhc2twYXNzd29yZA==  # flaskpassword (Base64 encoded)
  uri: bW9uZ29kYjovL2ZsYXNrLXVzZXI6Zmxhc2twYXNzd29yZEBtb25nb2RiLXNlcnZpY2U6MjcwMTcvY2xpZW50c19kYj9hdXRoU291cmNlPWFkbWlu  # mongodb://flask-user:flaskpassword@mongodb-service:27017/clients_db?authSource=admin
