apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: gauravkaushal1996/flask-clients-api:latest  
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://flask-user:flaskpassword@mongodb-service:27017/clients_db?authSource=admin"
