apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flask-api-tls
spec:
  secretName: flask-api-tls
  dnsNames:
    - clients.api.deltacapita.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
