name: Flask API CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: flask_user
          MONGO_INITDB_ROOT_PASSWORD: flaskpassword
          MONGO_INITDB_DATABASE: clients_db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MongoDB to be ready
        run: |
          sleep 10  # Give MongoDB time to start
          mongo --host localhost --eval "db.stats()" || exit 1

      - name: Run tests
        env:
          MONGO_URI: mongodb://flask_user:flaskpassword@localhost:27017/clients_db
        run: |
          PYTHONPATH=. pytest tests/
